spring:
  application:
    name: consumer-client
  datasource:
    username: root
    password: root
    url: jdbc:mysql://106.13.10.6:3306/ouath2?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    type:
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 7778
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8888}/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
